from tkinter import *
import random
import ttkthemes
from tkinter import ttk
root=ttkthemes.ThemedTk()
root.get_themes()
root.set_theme('radiance')
root.geometry('940x735+200+10')
root.resizable(0,0)
mainframe=Frame(root, bd=4)
mainframe.grid()
titleframe=Frame(mainframe, bg='orange')
titleframe.grid(row=0, column=0)
titlelabel=Label(titleframe, text='Typing Test', font=('algerian', 28, 'bold' ), bg='goldenrod3', fg='white', width='42')
titlelabel.grid(row=0, column=0, pady=5)
paraframe=Frame(mainframe)
paraframe.grid(row=1, column=0)
paragraph_list=['Artificial intelligence Machine Learning.Deep Learning being and'
'Artificial intelligence is to making machine to thinking the intelligence thing.'
'Machine learning is the techonolgy.intelligence machine can think new think and '
'Machine learning is tech to implement AI that can learn from data by themselves '
'Deep learning is the fiel of machne learning  that uses ANN to learn from the '
'It is a program that analyse the data and learns to predict the outcomes make.'
             ]
random.shuffle(paragraph_list)
label_paragraph=Label(paraframe, text=paragraph_list[0], wraplength=912, justify=LEFT, font=('arial', 14, 'bold'))
label_paragraph.grid(row=0, column=0)
textarea=Frame(mainframe)
textarea.grid(row=2, column=0)
text=Text(textarea, font=('arial', 12, 'bold'), width=100, height=7, bd=4, relief=GROOVE, wrap='word', state=DISABLED)

text.grid()
framoutput=Frame(mainframe)
framoutput.grid(row=3, column=0)
elapsed_time_label=Label(framoutput, text='Elapsed Time', font=('Tahoma', 12, 'bold'), fg='red')
elapsed_time_label.grid(row=0, column=0, padx=5)
elapsed_timer_label=Label(framoutput, text='0', font=('Tahoma', 12, 'bold'))
elapsed_timer_label.grid(row=0, column=1, padx=5)
remaining_time_label=Label(framoutput, text='Remaining Time', font=('Tahoma', 12, 'bold'), fg='red')
remaining_time_label.grid(row=0, column=2, padx=5)
remaning_timer_label=Label(framoutput, text='60', font=('Tahoma', 12, 'bold'))
remaning_timer_label.grid(row=0, column=3, padx=5)
wpm_label=Label(framoutput, text='WPM', font=('Tahoma', 12, 'bold'), fg='red')
wpm_label.grid(row=0, column=4)
wpmcount_label=Label(framoutput, text='60', font=('Tahoma', 12, 'bold'))
wpmcount_label.grid(row=0, column=5, padx=5)
totalwords_label=Label(framoutput, text='Total Words', font=('Tahoma', 12, 'bold'), fg='red')
totalwords_label.grid(row=0, column=6)
totalcount_label=Label(framoutput, text='0', font=('Tahoma', 12, 'bold'))
totalcount_label.grid(row=0, column=7, padx=5)
wrongwords_label=Label(framoutput, text='Wrong Words', font=('Tahoma', 12, 'bold'), fg='red')
wrongwords_label.grid(row=0, column=8)
wrongcount_label=Label(framoutput, text='0', font=('Tahoma', 12, 'bold'))
wrongcount_label.grid(row=0, column=9, padx=5)
accuracy_label=Label(framoutput, text='Accuracy', font=('Tahoma', 12, 'bold'), fg='red')
accuracy_label.grid(row=0,column=10, padx=5)
accuper_label=Label(framoutput, text='0', font=('Tahoma', 12, 'bold'))
accuper_label.grid(row=0, column=11, padx=5)
buttons_frame=Frame(mainframe)
buttons_frame.grid(row=4, column=0)
startbutton=ttk.Button(buttons_frame, text='Start')
startbutton.grid(row=0, column=0, padx=25, pady=10)
resetbutton=ttk.Button(buttons_frame, text='Reset', state=DISABLED)

resetbutton.grid(row=0, column=1, padx=25, pady=10)
exitbutton=ttk.Button(buttons_frame, text='Exit')
exitbutton.grid(row=0, column=2, padx=25, pady=10)
keyboard_frame=Frame(mainframe)
keyboard_frame.grid(row=5, column=0)
frame1to0=Frame(keyboard_frame)
frame1to0.grid(row=0, column=0,  pady=3)
label1=Label(frame1to0, text='1', bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
label2=Label(frame1to0, text='2', bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
label3=Label(frame1to0, text='3', bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
label4=Label(frame1to0, text='4', bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
label5=Label(frame1to0, text='5', bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
label6=Label(frame1to0, text='6', bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
label7=Label(frame1to0, text='7', bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
label8=Label(frame1to0, text='8', bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
label9=Label(frame1to0, text='9', bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
label0=Label(frame1to0, text='0', bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
#label1=Label(frame1to0, text='1', bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
label1.grid(row=0, column=0,padx=5)
label2.grid(row=0, column=1,padx=5)
label3.grid(row=0, column=2,padx=5)
label4.grid(row=0, column=3,padx=5)
label5.grid(row=0, column=4,padx=5)
label6.grid(row=0, column=5,padx=5)
label7.grid(row=0, column=6,padx=5)
label8.grid(row=0, column=7,padx=5)
label9.grid(row=0, column=8,padx=5)
label0.grid(row=0, column=9,padx=5)
frameqtop=Frame(keyboard_frame)
frameqtop.grid(row=1, column=0, pady=3)
labelQ=Label(frameqtop, text='Q',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelW=Label(frameqtop, text='W',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelE=Label(frameqtop, text='E',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelR=Label(frameqtop, text='R',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelT=Label(frameqtop, text='T',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelY=Label(frameqtop, text='Y',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelU=Label(frameqtop, text='U',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelI=Label(frameqtop, text='I',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelO=Label(frameqtop, text='O',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelP=Label(frameqtop, text='P',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelQ.grid(row=0, column=0,padx=5)
labelW.grid(row=0, column=1,padx=5)
labelE.grid(row=0, column=2,padx=5)
labelR.grid(row=0, column=3,padx=5)
labelT.grid(row=0, column=4,padx=5)
labelY.grid(row=0, column=5,padx=5)
labelU.grid(row=0, column=6,padx=5)
labelI.grid(row=0, column=7,padx=5)
labelO.grid(row=0, column=8,padx=5)
labelP.grid(row=0, column=9,padx=5)
frameptol=Frame(keyboard_frame)
frameptol.grid(row=2, column=0, pady=3)
labelA=Label(frameptol, text='A',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelS=Label(frameptol, text='S',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelD=Label(frameptol, text='D',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelF=Label(frameptol, text='F',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelG=Label(frameptol, text='G',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelH=Label(frameptol, text='H',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelJ=Label(frameptol, text='J',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelK=Label(frameptol, text='K',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelL=Label(frameptol, text='L',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelA.grid(row=0, column=0,padx=5)
labelS.grid(row=0, column=1,padx=5)
labelD.grid(row=0, column=2,padx=5)
labelF.grid(row=0, column=3,padx=5)
labelG.grid(row=0, column=4,padx=5)
labelH.grid(row=0, column=5,padx=5)
labelJ.grid(row=0, column=6,padx=5)
labelK.grid(row=0, column=7,padx=5)
labelL.grid(row=0, column=8,padx=5)
frameztom=Frame(keyboard_frame)
frameztom.grid(row=3, column=0, pady=3)
labelZ=Label(frameztom, text='A',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelX=Label(frameztom, text='S',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelC=Label(frameztom, text='D',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelV=Label(frameztom, text='F',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelB=Label(frameztom, text='G',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelN=Label(frameztom, text='H',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelM=Label(frameztom, text='J',bg='black', fg='white', font=('arial', 10, 'bold'), width=5, height=2, bd=10, relief=GROOVE)
labelZ.grid(row=0, column=2,padx=5)
labelX.grid(row=0, column=3,padx=5)
labelC.grid(row=0, column=4,padx=5)
labelV.grid(row=0, column=5,padx=5)
labelB.grid(row=0, column=6,padx=5)
labelN.grid(row=0, column=7,padx=5)
labelM.grid(row=0, column=8,padx=5)
spaceFrame=Frame(keyboard_frame)
spaceFrame.grid(row=4, column=0, pady=3)
labelSpace=Label(spaceFrame,text='',bg='black', fg='white', font=('arial', 10, 'bold'), width=40, height=2, bd=10, relief=GROOVE)
labelSpace.grid(row=0, column=0)
def changeBG(widget):
    widget.config(bg='blue')
list_numbers=[label1,label0,label2,label3,label4,label5, label6,label7, label8, label9]
list_alphabets=[labelA,labelM, labelN,labelB, labelV, labelC, labelZ, labelX, labelK, labelL, labelG, labelS, labelD
    , labelQ,labelW,labelR, labelT, labelY, labelU, labelI, labelO, labelP,labelE,labelF,labelJ]
space_label=[labelSpace]
binding_numbers=['1','2','3','4','5','6','7','8','9','0']
binding_letters=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
binding_smallletters=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
for numbers in range(len(binding_numbers)):
    root.bind(binding_numbers[numbers], lambda  event, label=list_numbers[numbers]:changeBG(label))
root.mainloop()